// ============================================================
// src/routes/pages.js
// HTML page routes.  Every route here renders an EJS template and
// returns text/html.  API routes live under routes/api/*.
//
// All page routes are optional-auth for now: they render even when
// no user is signed in.  Later phases can swap attachUser for a
// stricter requireAuth guard.
// ============================================================

const express = require("express");

const { renderLayout } = require("../lib/renderLayout");
const { getMockRail } = require("../data/mockRail");

const router = express.Router();

// -----------------------------------------------------------
// Root: redirect to the default tab.
// -----------------------------------------------------------
router.get("/", (_req, res) => {
  res.redirect("/chat");
});

// -----------------------------------------------------------
// Main navigation pages.
// Each one supplies its own activeNav + page + sidebar rail.
// -----------------------------------------------------------
router.get("/chat", (_req, res) => {
  renderLayout(res, {
    title: "Chat",
    activeNav: "chat",
    page: "chat",
    rail: getMockRail("chat"),
  });
});

router.get("/tasks", (_req, res) => {
  renderLayout(res, {
    title: "Tasks",
    activeNav: "tasks",
    page: "task",
    rail: getMockRail("tasks"),
  });
});

router.get("/calendar", (_req, res) => {
  renderLayout(res, {
    title: "Calendar",
    activeNav: "calendar",
    page: "calendar",
    rail: getMockRail("calendar"),
  });
});

router.get("/notes", (_req, res) => {
  renderLayout(res, {
    title: "Notes",
    activeNav: "notes",
    page: "note",
    rail: getMockRail("notes"),
  });
});

router.get("/search", (req, res) => {
  const query = String(req.query.q || "").trim();
  const normalizedQuery = query.toLowerCase();

  const demoNotes = [
    {
      id: "n1",
      title: "DevOps CA2 spec",
      preview: "Butler must combine tasks, calendar, notes, and AI chat into one workspace.",
      body: "# DevOps CA2 spec\n\n- Bring tasks, calendar, notes, and AI chat together.\n- Keep the experience calm and visually clear.\n- Record the final reflection for the hand-in.",
      updated: "5 min ago",
    },
    {
      id: "n2",
      title: "React → EJS mapping",
      preview: "ChatCanvas.tsx maps to pages/chat.ejs plus the shared shell.js behaviour.",
      body: "# React → EJS mapping\n\n- Use the current layout shell for the main app chrome.\n- Reuse the chat stream logic and the existing state container.\n- Keep the styling system consistent across the workspace.",
      updated: "1 hour ago",
    },
    {
      id: "n3",
      title: "Ideas for the data panel",
      preview: "Small charts, generated by AI, saved as custom panels for the weekly review.",
      body: "# Ideas for the data panel\n\n- Generate a tiny insight card for task completion.\n- Highlight the daily focus trend.\n- Save the best view as a custom panel.",
      updated: "Yesterday",
    },
  ];

  const demoTasks = [
    {
      id: "t1",
      title: "Finish DevOps CA2 report",
      due: "Today",
      priority: "high",
      done: false,
      description: "Polish the study dashboard, finalise the report, and prepare the hand-in summary.",
    },
    {
      id: "t2",
      title: "Review React → EJS mapping",
      due: "Tomorrow",
      priority: "medium",
      done: false,
      description: "Revisit the component architecture and map each UI concept to the current server-rendered shell.",
    },
    {
      id: "t3",
      title: "Push initial commit",
      due: "This week",
      priority: "low",
      done: false,
      description: "Package the current milestone and share the progress update with the team.",
    },
    {
      id: "t4",
      title: "Read Butler style.css",
      due: "Done",
      priority: "low",
      done: true,
      description: "Review the shared styling system for later UI improvements.",
    },
  ];

  const demoChats = [
    { id: "s-001", title: "Study plan for finals" },
    { id: "s-002", title: "Refactor Butler layout" },
    { id: "s-003", title: "Ideas for data panel" },
  ];

  const searchMatch = (text) => text.toLowerCase().includes(normalizedQuery);

  const notes = normalizedQuery
    ? demoNotes.filter((note) => searchMatch(note.title) || searchMatch(note.preview) || searchMatch(note.body))
    : [];

  const tasks = normalizedQuery
    ? demoTasks.filter((task) => searchMatch(task.title) || searchMatch(task.description))
    : [];

  const chats = normalizedQuery
    ? demoChats.filter((chat) => searchMatch(chat.title))
    : [];

  renderLayout(res, {
    title: query ? `Search results for "${query}"` : "Search — Butler",
    activeNav: "search",
    page: "search",
    searchQuery: query,
    pageLocals: {
      query,
      results: { notes, tasks, chats },
    },
  });
});

// -----------------------------------------------------------
// Legacy path aliases.  Kept so older bookmarks still work.
// -----------------------------------------------------------
router.get("/ai/chat", (_req, res) => res.redirect("/chat"));
router.get("/study/dashboard", (_req, res) => res.redirect("/tasks"));

// -----------------------------------------------------------
// Standalone auth pages (no layout shell).
// -----------------------------------------------------------
router.get("/auth/login", (_req, res) => {
  res.render("auth/login", {
    title: "Sign in — Butler",
    lang: "en",
    // Match the app's default paper/parchment aesthetic.
    theme: "retro",
  });
});

// -----------------------------------------------------------
// Preferences page.  Standalone (no layout shell) so it works
// even when other app state is not ready yet.  For now it only
// offers theme switching; persistence is client-side only.
// -----------------------------------------------------------
router.get("/preferences", (_req, res) => {
  res.render("preferences", {
    title: "Preferences — Butler",
    lang: "en",
  });
});

module.exports = router;
