apiVersion: v1
kind: Namespace
metadata:
  name: butler-production
  labels:
    app.kubernetes.io/name: butler
    app.kubernetes.io/environment: production
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
