# Owner: Yu Fei - K3s and Monitoring
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - prometheus-service.yaml
  - prometheus-rbac.yaml
  - servicemonitor.yaml
  - prometheus.yaml
  - prometheusrule.yaml
  - ingress.yaml
  - hpa.yaml
  - pdb.yaml
  - networkpolicy.yaml
