apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: butler
  labels:
    app.kubernetes.io/name: butler
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: butler
      app.kubernetes.io/component: web
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              app.kubernetes.io/name: traefik
      ports:
        - protocol: TCP
          port: 3000
    - from:
        - podSelector:
            matchLabels:
              prometheus: butler
      ports:
        - protocol: TCP
          port: 9090
        - protocol: TCP
          port: 9216
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
      ports:
        - protocol: TCP
          port: 443
        - protocol: TCP
          port: 27017
