apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: butler
  labels:
    app.kubernetes.io/name: butler
    app.kubernetes.io/component: web
spec:
  serviceMonitorSelector:
    matchLabels:
      app.kubernetes.io/name: butler
      app.kubernetes.io/component: web
  serviceMonitorNamespaceSelector: {}
  ruleSelector:
    matchLabels:
      app.kubernetes.io/name: butler
      app.kubernetes.io/component: web
  remoteWrite:
    - url: https://prometheus-prod-37-prod-ap-southeast-1.grafana.net/api/prom/push
      basicAuth:
        username:
          name: butler-runtime
          key: PROMETHEUS_USERNAME
        password:
          name: butler-runtime
          key: PROMETHEUS_API_KEY
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 250m
      memory: 512Mi
  retention: 24h
