apiVersion: v1
kind: Service
metadata:
  name: butler
  labels:
    app.kubernetes.io/name: butler
    app.kubernetes.io/component: web
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: butler
    app.kubernetes.io/component: web
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
    - name: metrics
      port: 9090
      targetPort: metrics
      protocol: TCP
    - name: mongodb-metrics
      port: 9216
      targetPort: mongodb-metrics
      protocol: TCP
